# Generated by Django 3.2.13 on 2023-10-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libkeyword', '0010_libkeyword_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libkeyword',
            name='category',
            field=models.IntegerField(default=1, help_text='keyword category'),
        ),
        migrations.AlterField(
            model_name='libkeyword',
            name='status',
            field=models.IntegerField(default=0, help_text='module status'),
        ),
    ]
