# Generated by Django 3.2.13 on 2023-10-16 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libkeyword', '0011_auto_20231016_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libkeyword',
            name='ext_name',
            field=models.CharField(help_text='external name', max_length=255, unique=True),
        ),
    ]
