# Generated by Django 3.2.13 on 2023-10-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0005_remove_region_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='status',
            field=models.IntegerField(default=0, help_text='module status'),
        ),
    ]
