# Generated by Django 3.2.13 on 2023-10-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectversion', '0003_auto_20230423_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectversion',
            name='status',
            field=models.IntegerField(default=0, help_text='module status'),
        ),
    ]
