# Generated by Django 3.2.13 on 2023-10-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userkeyword', '0003_auto_20230618_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userkeyword',
            name='status',
            field=models.IntegerField(default=0, help_text='module status'),
        ),
    ]
