# Generated by Django 3.2.13 on 2023-10-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildhistory', '0004_alter_buildhistory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildhistory',
            name='status',
            field=models.IntegerField(default=-1, help_text='build status'),
        ),
    ]
