# Generated by Django 3.2.13 on 2023-10-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcase', '0007_auto_20230920_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='status',
            field=models.IntegerField(default=0, help_text='module status'),
        ),
    ]
